name: vpt_vit_tiny_backdoor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.11.17=h56e8100_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - chardet=4.0.0=py310haa95532_1003
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=41.0.3=py310h89fc84f_0
  - cuda-cccl=12.3.52=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.52=0
  - cuda-opencl-dev=12.3.52=0
  - cuda-profiler-api=12.3.52=0
  - cuda-runtime=12.1.0=0
  - debugpy=1.8.0=py310h00ffb61_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py310haa95532_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.26.0=pyha63f2e9_0
  - ipython=8.18.1=pyh5737063_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310h5588dad_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.4.52=0
  - libcurand-dev=10.3.4.52=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpmath=1.3.0=py310haa95532_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - numpy-base=1.26.0=py310h65a83cf_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.2.0=hcfcfb64_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3=py310haa95532_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.1.0=py3.10_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h2bbff1b_0
  - pyzmq=25.1.1=py310h2849c00_2
  - requests=2.31.0=py310haa95532_0
  - setuptools=68.0.0=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.3.3=py310h8d17308_1
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310haa95532_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.41.2=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h63175ca_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==1.4.0
      - appdirs==1.4.4
      - array-record==0.4.1
      - astunparse==1.6.3
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.5.2
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.44.1
      - fsspec==2023.10.0
      - fvcore==0.1.5.post20221221
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.61.0
      - grpcio==1.59.2
      - h5py==3.10.0
      - importlib-resources==6.1.1
      - iopath==0.1.10
      - joblib==1.3.2
      - keras==2.14.0
      - keras-core==0.1.7
      - keras-cv==0.6.4
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - namex==0.0.7
      - networkx==3.2.1
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - pandas==2.1.3
      - pillow==10.1.0
      - portalocker==2.8.2
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pywin32==306
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - rich==13.6.0
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - simplejson==3.19.2
      - smmap==5.0.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-addons==0.22.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.14.0
      - tensorflow-intel==2.14.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.14.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - timm==0.4.12
      - toml==0.10.2
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - typeguard==2.13.3
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - wandb==0.16.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - yacs==0.1.8
prefix: E:\Program\MiniCondaEnviornments\vpt_vit_tiny_backdoor
