wandb_version: 1

SEED:
  desc: null
  value: 223
DATASET:
  desc: null
  value:
    datadir: /datasets
    num_classes: 10
    dataname: CIFAR10
    img_size: 224
    mean:
    - 0.4914
    - 0.4822
    - 0.4465
    std:
    - 0.247
    - 0.2435
    - 0.2616
OPTIMIZER:
  desc: null
  value:
    opt_name: SGD
    params:
      lr: 0.01
      weight_decay: 0.0001
TRAINING:
  desc: null
  value:
    batch_size: 128
    test_batch_size: 256
    epochs: 100
    log_interval: 1
    use_scheduler: true
    use_wandb: true
RESULT:
  desc: null
  value:
    savedir: ./saved_model
MODEL:
  desc: null
  value:
    modelname: vit_tiny_patch16_224_in21k
    prompt_type: shallow
    prompt_tokens: 1
    prompt_dropout: 0.0
EXP_NAME:
  desc: null
  value: vit_tiny_patch16_224_in21k-shallow-n_prompts1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701305819.231768
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 63
      2:
      - 1
      - 41
      - 51
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
