_BASE_: "../base-finetune.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordCars"
  DATAPATH: "E:/Development/OPTML Group/VPT_vitTINY/VPT_official_SLURM_linux/data/StanfordCars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
  FEATURE: "imagenet_supervised"  # need to tune
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.0375
  WEIGHT_DECAY: 0.001
